name: Actualizar Precios Canarias

on:
  schedule:
    - cron: '0 8 * * *'  # Se ejecuta todos los días a las 8:00 AM
  workflow_dispatch:      # Permite ejecutarlo a mano cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install requests pandas folium

      - name: Ejecutar script de precios
        run: python mapa_pro.py

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m "Actualización automática de precios: $(date)" || exit 0
          git push